// Pulls ABIs out of the Foundry build artifacts so the frontend can never drift from
// the deployed contracts. Run `npm run sync-abis` after any change under ../contracts/src.
import {mkdirSync, readFileSync, writeFileSync} from 'node:fs'
import {dirname, resolve} from 'node:path'
import {fileURLToPath} from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const outDir = resolve(here, '../../contracts/out')
const target = resolve(here, '../src/abi')

const CONTRACTS = ['WeirFactory', 'MerchantSplitter', 'WeirOffer', 'MockUSDT']

mkdirSync(target, {recursive: true})

const exports = []

for (const name of CONTRACTS) {
  const artifactPath = resolve(outDir, `${name}.sol`, `${name}.json`)
  let artifact
  try {
    artifact = JSON.parse(readFileSync(artifactPath, 'utf8'))
  } catch {
    console.error(`  missing artifact for ${name} — run \`forge build\` in ../contracts first`)
    process.exit(1)
  }

  const constName = `${name.charAt(0).toLowerCase()}${name.slice(1)}Abi`
  writeFileSync(
    resolve(target, `${name}.ts`),
    `// Generated by scripts/sync-abis.mjs — do not edit by hand.\n` +
      `export const ${constName} = ${JSON.stringify(artifact.abi, null, 2)} as const\n`,
  )
  exports.push(`export {${constName}} from './${name}'`)
  console.log(`  ${name} -> src/abi/${name}.ts`)
}

writeFileSync(
  resolve(target, 'index.ts'),
  `// Generated by scripts/sync-abis.mjs — do not edit by hand.\n${exports.join('\n')}\n`,
)
console.log('ABIs synced.')
